### PR TITLE
Fix MoreCulling compatibility

### PR DESCRIPTION
**Pull request by FxMorin**
https://github.com/fxmorin/MoreCulling/issues/65

### CODE REVIEW

**Comment by PweSol** [comment]
~Seems to be working fine. I also tried these changes for the 1.19 branch and it works as well.~

**Comment by PweSol** [comment]
Looks like there are still some issues. When DashLoader generates new cache, it works fine. But when starting the game again and loading the cache, some parts of the world don't load. Tested on 1.18 and 1.19
first load
second load

**Comment by FxMorin** [comment]
Is there anything in the logs?

**Comment by PweSol** [comment]
This is basically my session log. I have the issue with and without other mods, so here is it with most of my mods that I run, in case other mod caused it and disabling it doesn't help.
[latest.log](https://github.com/TeamQuantumFusion/DashLoader/files/9236460/latest.log)

**Comment by primesonaldo** [comment]
> Looks like there are still some issues. When DashLoader generates new cache, it works fine. But when starting the game again and loading the cache, some parts of the world don't load. Tested on 1.18 and 1.19 first load second load

I have the EXACT same issue, but only when I place an iron bar, somehow it is fixed when F3 + T and even when I recreate the world it does not glitch again. Sometimes the game crashes though.

**Pull request merged**
